"""
Add llm_provider_keys

Revision ID: 0003_add_llm_provider_keys
Revises: 0002_add_dataset_stats
Create Date: 2024-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_add_llm_provider_keys'
down_revision = '0002_add_dataset_stats'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_provider_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_provider_keys')
    # ### end Alembic commands ###
